name: fabler_icons
description: set of Tabler icons for flutter platforms
repository: https://github.com/miladimos/fabler_icons
homepage: https://github.com/miladimos/fabler_icons

version: 1.2.5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: tabler-icons
      fonts:
        - asset: assets/fonts/tabler-icons.ttf
          style: normal
          weight: 400
